#
#          _____                    _____                    _____                _____                    _____                    _____          
#         /\    \                  /\    \                  /\    \              |\    \                  /\    \                  /\    \         
#        /::\    \                /::\    \                /::\____\             |:\____\                /::\    \                /::\    \        
#       /::::\    \              /::::\    \              /::::|   |             |::|   |                \:::\    \               \:::\    \       
#      /::::::\    \            /::::::\    \            /:::::|   |             |::|   |                 \:::\    \               \:::\    \      
#     /:::/\:::\    \          /:::/\:::\    \          /::::::|   |             |::|   |                  \:::\    \               \:::\    \     
#    /:::/__\:::\    \        /:::/__\:::\    \        /:::/|::|   |             |::|   |                   \:::\    \               \:::\    \    
#   /::::\   \:::\    \      /::::\   \:::\    \      /:::/ |::|   |             |::|   |                   /::::\    \              /::::\    \   
#  /::::::\   \:::\    \    /::::::\   \:::\    \    /:::/  |::|   | _____       |::|___|______    _____   /::::::\    \    ____    /::::::\    \  
# /:::/\:::\   \:::\ ___\  /:::/\:::\   \:::\    \  /:::/   |::|   |/\    \      /::::::::\    \  /\    \ /:::/\:::\    \  /\   \  /:::/\:::\    \ 
#/:::/__\:::\   \:::|    |/:::/__\:::\   \:::\____\/:: /    |::|   /::\____\    /::::::::::\____\/::\    /:::/  \:::\____\/::\   \/:::/  \:::\____\
#\:::\   \:::\  /:::|____|\:::\   \:::\   \::/    /\::/    /|::|  /:::/    /   /:::/~~~~/~~      \:::\  /:::/    \::/    /\:::\  /:::/    \::/    /
# \:::\   \:::\/:::/    /  \:::\   \:::\   \/____/  \/____/ |::| /:::/    /   /:::/    /          \:::\/:::/    / \/____/  \:::\/:::/    / \/____/ 
#  \:::\   \::::::/    /    \:::\   \:::\    \              |::|/:::/    /   /:::/    /            \::::::/    /            \::::::/    /          
#   \:::\   \::::/    /      \:::\   \:::\____\             |::::::/    /   /:::/    /              \::::/    /              \::::/____/           
#    \:::\  /:::/    /        \:::\   \::/    /             |:::::/    /    \::/    /                \::/    /                \:::\    \           
#     \:::\/:::/    /          \:::\   \/____/              |::::/    /      \/____/                  \/____/                  \:::\    \          
#      \::::::/    /            \:::\    \                  /:::/    /                                                          \:::\    \         
#       \::::/    /              \:::\____\                /:::/    /                                                            \:::\____\        
#        \::/____/                \::/    /                \::/    /                                                              \::/    /        
#         ~~                       \/____/                  \/____/                                                                \/____/         
#                                                                                                                                              
#
#								 	  					 ZetrexNetwork [BanGUI] Configuration
#					        				 	         Responsible For: Apply user Settings
#								  	    				     Last Official Update: 08/6/20 
#									
#
# 								  		  							  Color Codes:
#
# 						       							         BLACK: &0 | DARK_GRAY: &8
# 						      							     DARK_BLUE: &1 | BLUE: &9
#					  	 						            DARK_GREEN: &2 | GREEN: &a
#						      							     DARK_AQUA: &3 | AQUA: &b
#						       							      DARK_RED: &4 | RED: &c
#						   						           DARK_PURPLE: &5 | LIGHT_PURPLE: &d
#						           						          GOLD: &6 | YELLOW: &e
#						           					              GRAY: &7 | DARK_GRAY: &8
#
# 						       						             WHITE: &f | BOLD: &l
# 						       						             MAGIC: &k | STRIKETHROUGH: &m
# 						       						         UNDERLINE: &n | ITALIC: &o
#
# 						       									 	    RESET: &r 
#
#
#															         TROUBLESHOOTING: 
#
#                                                    1) Check for unnecessary indents, tabs and spaces.
#                                                    2) Check for unclosed quotations or apostrophes.
#                                                    3) Ensure use of  double 's.
#                                                    4) Ensure you keep variables such as "{0}".
#                                                    5) DM #benyji#4392 with your issue.
#
# What would you like the title of the GUI to be?
guiTitle: '&0&lZetrexNetwork &b[Ban GUI]'
#
#											 				   ALPHABETICAL ORDER A-Z, 0-9
#
#                                                                   NAME CONFIGURATION
# What should the display name of Advertising be on the GUI?
advertising_display_name: '&bAdvertising'
# What should the display name of 'AFK / Autoclicker' be on the GUI?
afk_display_name: '&bAFK/ Autoclicker'
# What should the display name of Anti Knockback be on the GUI?
anti_kb_display_name: '&bAnti-Knockback'
# What should the name of combat exploits be on the GUI?
combat_display_name: '&bKillaura / TP Aura'
# What should Hacked Creative Items be on the GUI?
creative_display_name: '&bHacked Creative Items'
# What should the name of Criticals to be on the GUI?
criticals_display_name: '&bCriticals'
# What should the name of 'DDoS Threat / Crash Attempt' be on the GUI?
ddos_display_name: '&bDDOS Threat / Crash Attempt'
# What should the name of 'Derp / Crouch / Skin Blinker' be on the GUI?
derp_display_name: '&bDerp / Crouch / Skin Blinker'
# What should the name of 'Hate / discrimination' be on the GUI?
discrimination_display_name: '&bHate / Discrimination'
# What should the name of standard exploits be on the GUI?
exploit_display_name: '&bX-Ray[BASES] / Exploiting'
# What should the name of Extreme Harassment be on the GUI?
extreme_display_name: '&bExcessive Harassment'
# What should the name of griefing be on the GUI?
griefing_display_name: '&bGriefing'
# What should the name of Harassment be on the GUI?
harassment_display_name: '&bHarassment'
# What should the name of 'Staff Impersonation / Disrespect' be on the GUI?
impersonation_display_name: '&bStaff Impersonation / Disrespect'
# What should the name of 'Inappropriate Skin / Name' be on the GUI?
inappropriate_display_name: '&bInappropriate Name / Skin'
# What should the name of Scaffold exploit be on the GUI?
scaffold_display_name: '&bScaffold' 
# What should the name of Sexual Harrasment be on the GUI?
sexual_harrasment_display_name: '&bSexual Harrassment'
# What should the name of mining exploits be on the GUI
mining_display_name: '&bFast Break / Place / Nuker / Auto Tool'
# What should the name of Minor Repeat Offenses be on the GUI?
minor_display_name: '&bRepeated Minor Offenses'
# What should the name of movement exploits be on the GUI?
movement_display_name: '&bFly / Speed / No-Fall / Jesus'
# What should the name of Lag Machine exploit be on the GUI?
lag_machine_display_name: '&bLag Machine'
# What should the name of 'Phase/ Freecam/ Glitching' be on the GUI?
phase_display_name: '&bPhase / Freecam / Glitching'
# What should the name of 'X-Ray Ores/ Dungeons' be on the GUI?
xray_display_name: '&bX-Ray[ORES] / Dungeons'
#
#                                                                   ICON CONFIGURATION
#                                   List of icon names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#
# What should the icon of advertising be on the GUI?
advertising_icon: 'SIGN'
# What should the icon of 'AFK / Autoclicker' be on the GUI?
afk_icon: 'STONE_BUTTON'
# What should the icon of Anti Knockback be on the GUI?
anti_kb_icon: 'EGG'
# What should the icon of combat exploits be on the GUI?
combat_icon: 'DIAMOND_SWORD'
# What should the icon of Hacked Creative Items be on the GUI?
creative_icon: 'DIAMOND'
# What should the icon of Criticals to be on the GUI?
criticals_icon: 'NETHER_STALK'
# What should the icon of 'DDOS / Crash Attempt' be on the GUI?
ddos_icon: 'REDSTONE'
# What should the name of 'Derp / Crouch / Skin Blinker' be on the GUI?
derp_icon: 'DIRT'
# What should the icon of 'Hate / Discrimination be on the GUI?
discrimination_icon: 'JACK_O_LANTERN'
# What should the icon of standard exploits be on the GUI?
exploit_icon: 'CHEST'
# What should the icon of Extreme Harassment be on the GUI?
extreme_icon: 'YELLOW_DYE'
# What should the icon of griefing be on the GUI?
griefing_icon: 'LAVA_BUCKET'
# What should the icon of harrassment be on the GUI?
harassment_icon: 'ROTTEN_FLESH'
# What should the icon of 'Staff Impersonation / Disrespect' be on the GUI?
impersonation_icon: 'TRIPWIRE_HOOK'
# What should the icon of 'Inappropriate Name / Skin' be on the GUI?
inappropriate_icon: 'PAINTING'
# What should the icon of Scaffold exploit be on the GUI?
scaffold_icon: 'STONE'
# What should the icon of Sexual Harrasment be on the GUI?
sexual_harrasment_icon: 'GOLDEN_CARROT'
# What should the icon of mining exploits be on the GUI?
mining_icon: 'DIAMOND_PICKAXE'
# What should the icon of Minor Repeat Offenses be on the GUI?
minor_icon: 'INC_SACK, 1, (byte) 5'
# What Should the icon of movement exploits be on the GUI?
movement_icon: 'FEATHER'
# What should the icon of Lag Machine be on the GUI?
lag_machine_icon: 'PISTON_STICKY_BASE' 
# What should the icon of 'Phase/ Freecam/ Glitching' be on the GUI?
phase_icon: 'COMPASS'
# What should the icon of 'X-Ray Ores/ Dungeons' be on the GUI?
xray_icon: 'DIAMOND_ORE'
